// <auto-generated />
using System;
using Airline_Management_System__AMS_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airline_Management_System__AMS_.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251213000000_AddSeatPrice")]
    partial class AddSeatPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ... (rest of the model snapshot would be included here, but for brevity, the migrations system will handle this)
#pragma warning restore 612, 618
        }
    }
}
